// file generated by the Paraglide-Next init command
import * as m from "@/paraglide/messages";
import type { AvailableLanguageTag } from "@/paraglide/runtime";
import { Middleware, Navigation, PrefixStrategy } from "@inlang/paraglide-next";

const strategy = PrefixStrategy<AvailableLanguageTag>({
  prefixDefault: "never",
  pathnames: {
    "/login": m.watery_icy_shrimp_absorb,
    "/waves": m.smug_key_lionfish_emerge,
    "/orders": m.wacky_just_blackbird_clasp,
    "/skus": m.solid_just_monkey_dance,
    "/logs": m.vivid_that_squirrel_nourish,
  },
});

export const middleware = Middleware({ strategy });
export const { Link, useRouter, usePathname, redirect, permanentRedirect } =
  Navigation({
    strategy,
  });
